### ISSUE TITLE
convert expects numpy arrays in non-ndio approved order?

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#133]
| ndio version | os | python |
| --- | --- | --- |
| 0.1.13 | * | * |

as far as I can surmise, convert functions are broken because they expect zyx and not xyz.  Verify and fix?

**Comment by j6k4m8** [comment]
aw butts. confirmed. adding it to my **<kbd>this-week</kbd>**. PRs obviously welcome

**Comment by wrgr** [comment]
Is this still broken?  Or did we decide it was just the higher level script?  Not sure, but let's resolve and close.

**Comment by j6k4m8** [comment]
I think the right answer is that this is still correct, and we just change how we call it.

**Comment by wrgr** [comment]
let's talk in 5 minutes.  :)  seems like I now have to have a transpose call, because png writers are doing yxz...let's talk and fix or close.

**Comment by j6k4m8** [comment]
yxz..?! ok i give up. from now on i'm ordering all ndio volumes as [zxyyz] . followed by either x or an invalid unicode character, depending on
current-millis-since-midnight % 2.

On Mon, Mar 7, 2016 at 12:54 PM William Gray notifications@github.com wrote:
let's talk in 5 minutes. :) seems like I now have to have a transpose call,
because png writers are doing yxz...let's talk and fix or close.

**Comment by wrgr** [comment]
ok - the way we are handling this is to assume users are passing in an xy slice or xyz volume.  And dealing with the transpose internal to convert.
