### ISSUE TITLE
ndio RAMON Id ordering

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#183]
| ndio version | os | python |
| --- | --- | --- |
| 1.0 | macosx | 2.7 |

nd.get_ramons come down in seemingly random order.  With the flattened structure, this makes it particularly hard to use/correlate.  Thoughts?  Example tomorrow in real time.

**Comment by j6k4m8** [comment]
options: 
- return a dictionary of `{ id: ramon, ... }` so you can say `nd.get_ramon(. . . )[YOUR_ID_HERE]`
- sort by ID, ascending (protip: ids have to be ints then)
- sort by ID, by index in the array that you pass to `get_ramon` (caveat: if any of them fail, this gets super screwed up because `len(results) != len(asks)`)

**Comment by j6k4m8** [comment]
@willgray I don't remember what we decided... `dict`?

**Comment by Aeusman** [comment]
Did this get implemented? Will close for now since Ramon ids appears fine to me after doing some light testing, happy to re-open/discuss.
