### ISSUE TITLE
auto-ingest script

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ndio#201]
I was reading through [data ingest documentation](http://docs.neurodata.io/ndstore/sphinx/ingesting.html), as I'm hoping to ingest 3D time-series data. I didn’t see the script for how to actually post the data through autoingest, though? Is `generatejson.py` that?

@kunallillaney @Aeusman

**Comment by jovo** [comment]
for reference, i tasked greg with ingesting some MRI data for ndpaper.
@gkiar  is smart, and on our team.
his question indicates that the ingest instructions are not sufficiently clear.
perhaps if they pointed to a working example in a jupyter notebook it would be clear.

@willgray @j6k4m8

**Comment by Aeusman** [comment]
@jovo I spoke with @gkiar and it looks like the confusion stemmed from the old naming of generatejson. I will rename the file in docs and ndstore to AutoIngest.py

**Comment by jovo** [comment]
and please post a link to a working jupyter notebook example.

On Wed, Jun 8, 2016 at 6:18 PM, Alex Eusman notifications@github.com
wrote:

> @jovo https://github.com/jovo I spoke with @gkiar
> https://github.com/gkiar and it looks like the confusion stemmed from
> the old naming of generatejson. I will rename the file in docs and ndstore
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/201#issuecomment-224644219, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcnxPksiH4zfHGKPFy9J_uIKVo4Ryks5qJus9gaJpZM4Iw-Op
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by kunallillaney** [comment]
@jovo We can have a jupyter notebook example which appears to work. The reason is that an ingest job can only be run once. Once the channel is created it has to be manually deleted before another ingest job for the same channel can be run. I discussed this with @Aeusman and he will enter real values in the notebook but disable the post command.

**Comment by jovo** [comment]
right, i understand that.
i'd like it to have worked once.
meaning it needs real values,
and real data that exists to post from.

and then yes, disable the post command.
thank you!

On Wed, Jun 8, 2016 at 6:23 PM, Kunal Lillaney notifications@github.com
wrote:

> @jovo https://github.com/jovo We can have a jupyter notebook example
> which appears to work. The reason is that an ingest job can only be run
> once. Once the channel is created it has to be manually deleted before
> another ingest job for the same channel can be run. I discussed this with
> @Aeusman https://github.com/Aeusman and he will enter real values in
> the notebook but disable the post command.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/201#issuecomment-224645890, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjchv9FQKNM79tnaiQTInrEsFkUclCks5qJuyagaJpZM4Iw-Op
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by kunallillaney** [comment]
Yes I agree and I have instructed him to do the same. So he will enter values for an existing public dataset which has been ingested.

**Comment by Aeusman** [comment]
https://github.com/neurodata/ndio-demos/blob/AddINgest/Archive/Getting%20Started/Auto-Ingesting%20A%20Volume.ipynb

I've re-written some descriptions and included real values, any thoughts?

**Comment by jovo** [comment]
great!

please

1) explain why the post is commented out
2) give an example including a couple metadata fields?

On Wed, Jun 8, 2016 at 7:11 PM, Alex Eusman notifications@github.com
wrote:

> https://github.com/neurodata/ndio-demos/blob/AddINgest/Archive/Getting%20Started/Auto-Ingesting%20A%20Volume.ipynb
> 
> I've re-written some descriptions and included real values, any thoughts?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/201#issuecomment-224661294, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjckcDBYub-UTsSPJn_ZAYMXNOoZLKks5qJvesgaJpZM4Iw-Op
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by Aeusman** [comment]
For 1 something like?:
For this example the post command has been commented out as calling it would trigger the data to be posted into our service. Because it is not possible to remove this data easily once posted, we have not enabled this step in the tutorial.

I think 2 may be an @j6k4m8 or @willgray question as I haven't used the LIMS schema, but if there are some docs somewhere I'd be happy to read them and create examples.

**Comment by kunallillaney** [comment]
@jovo As far as I know, the LIMS server is not active and we(me and @Aeusman) have never used it. So metadata has been an empty field so far.

**Comment by jovo** [comment]
@Aeusman great, put that somewhere that doesn't require @j6k4m8 or @willgray to approve it, because i don't know their process, and don't want to wait anymore

@kunallillaney ok, please push the docs changes now so they are live.

@willgray @j6k4m8 does ndlims work? if so, can you point @Aeusman to documentation so that he may add an example?

**Comment by wrgr** [comment]
ndlims is not something I supervised or could provide status.  I am very interested in such a thing and could help tell someone what properties would be good to exist - @j6k4m8?

**Comment by Aeusman** [comment]
@jovo I'll just put it in the ndio demos under the getting started archive unless @willgray there's a better place for it?

**Comment by wrgr** [comment]
i think it should live in its own thread on nddocs, i.e., not within ndio?

**Comment by wrgr** [comment]
like ndingest

**Comment by jovo** [comment]
i think nddocs is a fine place.

**Comment by Aeusman** [comment]
So place it in the nddocs area of ndstore? @kunallillaney is there a place you think it makes most sense?

**Comment by jovo** [comment]
i think that makes sense for now.

**Comment by j6k4m8** [comment]
Sorry about the comm lag on my end — LIMS is alive and is communicating with ndstore, as far as I was aware. I can't get [http://openconnecto.me/ocp/ca/bock11/info] to load, but my understanding is that [the metadata from LIMS](http://lims.neurodata.io/metadata/ocp/get/bock11) is populated correctly in the `.metadata` field.

@Aeusman, metadata can be edited through [`ndio.remote.neurodata#set_metadata()`](https://github.com/neurodata/ndio/blob/master/ndio/remote/neurodata.py#L277). Unless otherwise specified, all of the `secret`s are the word that I just sent to you via slack (any other ND'ers, I've documented this privately and am happy to share — this secret just prevents unauth'd edits of our LIMS). Let me know if you need any other pointers :)

**Comment by kunallillaney** [comment]
@j6k4m8 The bock11 info loads fine on my end but the metadata field is till empty. Can you please try again?

**Comment by wrgr** [comment]
bock access was temporarily broken earlier I think with the server reboot.  maybe good now?

**Comment by kunallillaney** [comment]
the info call for all datasets comes from 29 which has been up since I bought the service online today morning. Data is hosted on 62 which is still down. This should not affect the metadata or the info service in any way.

**Comment by j6k4m8** [comment]
Confirmed good now, although _crazy_ slow pingback times from Mt Vernon... 

Here's an asciicast (time-truncated) for a wget of a `/info` page, showing 1min download times:

[![asciicast](https://asciinema.org/a/0csltot0kk7rfrb4icg4ic1qv.png)](https://asciinema.org/a/0csltot0kk7rfrb4icg4ic1qv)

Sorry if that was a false alarm earlier.
@kunallillaney, we definitely had this working at one point — I think earlier this past (spring) semester. Did we roll back the ndstore `LIMS_URL`?

**_[EDIT]**_: [This commit in March](https://github.com/neurodata/ndstore/commit/c04396ce2c4c005715ed815cbc809a9d211ab475) disabled LIMS

**Comment by kunallillaney** [comment]
Yeah. I think we disabled it because it was not working. Is it now running and can we enable it?

On the network latency, that has been a pending issue with the hardware guys for 2 days now. Not your fault. :)

**Comment by j6k4m8** [comment]
Ah, awesome, glad to hear it's in the process of being fixed at least! (My homepage is ocp/bock11/info so this was really slowing down my browsing experience)

Definitely running now — I think it's been up nonstop but it's possible there were...ahem....hardware problems... Not that _that_ ever happens
