### ISSUE TITLE
ndingest.py: identify_imagesize non functional

### ISSUE THREAD

**Issue by adwanner** [openconnectome/ndio#209]
| ndio version | os | python |
| --- | --- | --- |
| 1.1.1 | ubuntu 14.04 | python 2.7 |

On lines 370 and 404 the indicated stack size (input parameter "imagesize" of autoingest.py) is validated against the actual image size. The function identify_imagesize should return the image size, but apparently returns the image itself. 
In addition, there might be problem in validating imagesize by just comparing the size of the image to imagesize. The parameter imagesize contains the stack size as (X,Y,Z), i.e. (width,height,depth).
For validation/ comparison, the depth/Z size should be included and one has to be careful about the order of the size information in imagesize (width,height,depth).

**Comment by Aeusman** [comment]
Absolutely right on the bug front, issuing a pr.

Right now we don't verify the Z dimension of the image sizes because this would double the amount of images we need to download/verify. Although it doesnt seem like a lot when running timseries data and needing to verify every time point this would be very cumbersome. 

The spirit of the verify is to provide a courtesy service to make sure you uploaded the correct xy dimensions, not make it harder to upload.

**Comment by Aeusman** [comment]
Fixed in latest pull
