### ISSUE TITLE
OCP & meta

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#24]
- [ ] let's remove OCP everywhere and replace with "nd"
- [ ] i think "meta" means "ndlims" now? if so, let's fix.

**Comment by j6k4m8** [comment]
I want to ultimately kill `ndio.remote.OCPMeta` once metadata loads
correctly through proj-info pages, which is why i haven't gone to the
trouble of editing it yet. (I think it's more intuitive for the LIMS
transactions to be entirely opaque to the user, indistinguishable from
writes to the spatial db) Happy to update this if that roll is not
forthcoming in the near future, though.

As for OCP: does that mean change `ndio.remote.OCP` to `ndio.remote.nd`? Or
perhaps `ndio.remote.neurodata`?

**Comment by alexbaden** [comment]
Might want to work "spdb" (spatial database) somewhere into the name.
ndio.nd.spdb or ndio.remote.spdb ?

**Comment by jovo** [comment]
yah, we need a cooler name for the spatial database.
for annotations, we have RamonDB
for graphs, we have GruteDB
what about AcantiDB?

**Comment by jovo** [comment]
@alexbaden is right that in the new branch, it is called `spdb`
too bad that name isn't cool.
@willgray can't you think of something better?

**Comment by j6k4m8** [comment]
Volumetric Information Organization for Large-scale-Infrastructure Neuroscience

violin

@willgray has taught me well

**Comment by j6k4m8** [comment]
- Database Repository for Annotation-Generation and Open Neuroscience (DRAGON)
- Low-Overhead Brain-science Engine (LOBE)
- Big-data Research Application for Interactive Neuroscience (BRAIN)
- SPAtial Database for Neuroscience Knowledge (SPANK)

**Comment by j6k4m8** [comment]
resolved in #94 :)
