### ISSUE TITLE
improve travis build speed

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ndio#28]
we do a LOT of building and downloading and installing for every build, and it feels like there must be a lot happening that doesn't need to happen. (see [this line](https://github.com/openconnectome/ndio/blob/master/.travis.yml#L6) for instance). Builds currently take 10 minutes on average — definitely fixable but I don't know how.

**Comment by j6k4m8** [comment]
@Aeusman do you have any thoughts on this?

**Comment by Aeusman** [comment]
@j6k4m8 Yeah, so I was pushing a lot of small fixes because I was multitasking and it was a good way to let things test in the background, now I'm testing on local machine. Not sure about the slowdown problem though, travis was having huge problems with load yesterday https://www.traviscistatus.com/ which leads me to guess this may not just be an us problem?

**Comment by Aeusman** [comment]
Of note: https://travis-ci.org/openconnectome/ndio/builds Increased time happens after 0.0.21

**Comment by j6k4m8** [comment]
we're `sudo apt-get update`ing every time which feels wrong, but i'm not sure we can avoid it

**Comment by Aeusman** [comment]
I think build speed is acceptable for now.
